### PR TITLE
Send email to collection managers when owner changed.

### LINKED ISSUE #2331: Change owner: Email notification: Collection managers: ownership of item in a collection has changed
See https://docs.google.com/document/d/1TZVILUrORI25kRZyUZ70vMQYo90Ngp_tqCI7BdU_VyQ/edit#heading=h.ko6440pvxvkt

Collection manager: Ownership of collection item changed
Note: send to all managers on a collection

Subject: The ownership of an item in your collection has changed

Dear [same salutation as used in other emails],

Ownership of the item "[item.name]" in your collection [collection.name] has changed. Click here [link to item view page] to view the change in the history table for this item.

If this person has also been added to the list of depositors for this collection if they were not already on the list.

If you have any questions, contact the SDR team at: http://sdr.stanford.edu/#help

The Stanford Digital Repository Team

### PR DESCRIPTION
**Pull request by justinlittman**
closes #2331

## How was this change tested? 🤨

⚡ ⚠ If this change involves consuming from or writing to another service (or shared file system), ***run [integration test create_object_h2_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test manually in [stage|qa] environment, in addition to specs. ⚡

Unit, QA

### CODE REVIEW

**Comment by justinlittman** [comment]
image

**Comment by jcoyne** [comment]
@justinlittman this needs a rebase.

**Review by ndushay — COMMENTED** [review]
I don't understand where this code is checking to see IF the owner has changed before sending email to the collections manager.

**Review by ndushay — APPROVED** [review]
is it properly scoped because it is in the work_owners_controller.update method?  (d'oh)

**Comment by justinlittman** [comment]
Yes, that is right @ndushay. As it turns out, the current code for the `update` method does not check if owner has changed but that is a separate ticket.

**Pull request merged**
