### PR TITLE
Adds erb linting.

### PR DESCRIPTION
**Pull request by justinlittman**
## Why was this change made? 🤔
Erbs can be messy code.

## How was this change tested? 🤨

⚡ ⚠ If this change involves consuming from or writing to another service (or shared file system), ***run [integration test create_object_h2_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test manually in [stage|qa] environment, in addition to specs. ⚡

### CODE REVIEW

**Comment by justinlittman** [comment]
Still outstanding:
```
bundle exec erblint --lint-all   
Linting 176 files with 16 linters...

erb interpolation with '<%= (...).html_safe %>' in this context is never safe
In file: app/components/works/agreement_component.html.erb:10

Input tag is missing an autocomplete attribute. If no autocomplete behaviour is desired, use the value `off` or `nope`.
In file: app/components/works/approval_component.html.erb:21

Input field helper is missing an autocomplete attribute. If no autocomplete behaviour is desired, use the value `off` or `nope`.
In file: app/components/works/dates_component.html.erb:32

Input tag is missing an autocomplete attribute. If no autocomplete behaviour is desired, use the value `off` or `nope`.
In file: app/components/works/purl_reservation_modal_component.html.erb:11

Input tag is missing an autocomplete attribute. If no autocomplete behaviour is desired, use the value `off` or `nope`.
In file: app/components/works/work_type_modal_component.html.erb:54

Rails/Date: Do not use `Date.today` without zone. Use `Time.zone.today` instead.
In file: app/views/admin/collection_reports/new.html.erb:18

Rails/Date: Do not use `Date.today` without zone. Use `Time.zone.today` instead.
In file: app/views/admin/collection_reports/new.html.erb:24

Rails/Date: Do not use `Date.today` without zone. Use `Time.zone.today` instead.
In file: app/views/admin/collection_reports/new.html.erb:33

Rails/Date: Do not use `Date.today` without zone. Use `Time.zone.today` instead.
In file: app/views/admin/collection_reports/new.html.erb:39

Rails/Date: Do not use `Date.today` without zone. Use `Time.zone.today` instead.
In file: app/views/admin/work_reports/new.html.erb:18

Rails/Date: Do not use `Date.today` without zone. Use `Time.zone.today` instead.
In file: app/views/admin/work_reports/new.html.erb:24

Rails/Date: Do not use `Date.today` without zone. Use `Time.zone.today` instead.
In file: app/views/admin/work_reports/new.html.erb:33

Rails/Date: Do not use `Date.today` without zone. Use `Time.zone.today` instead.
In file: app/views/admin/work_reports/new.html.erb:39

Rails/Date: Do not use `Date.today` without zone. Use `Time.zone.today` instead.
In file: app/views/admin/work_reports/new.html.erb:48

Rails/Date: Do not use `Date.today` without zone. Use `Time.zone.today` instead.
In file: app/views/admin/work_reports/new.html.erb:54

erb interpolation with '<%= (...).html_safe %>' in this context is never safe
In file: app/views/shared/_flashes.html.erb:18

Input tag is missing an autocomplete attribute. If no autocomplete behaviour is desired, use the value `off` or `nope`.
In file: app/views/welcome/show.html.erb:55

Input tag is missing an autocomplete attribute. If no autocomplete behaviour is desired, use the value `off` or `nope`.
In file: app/views/welcome/show.html.erb:57
```

**Review by mjgiarlo — APPROVED** [review]
Happy to pre-approve this so it gets merged once it's green.

**Comment by mjgiarlo** [comment]
@justinlittman Given we're touching the views a lot in this WC, I might like to see this move forward if you're up to rebasing this and taking it up again.

**Comment by mjgiarlo** [comment]
Superseded by #3115. Care to close this, @justinlittman ?

**Pull request closed without merging**
