### PR TITLE
detect changes to work_version associations correctly

### LINKED ISSUE #2304: Add additional descriptions to item history table for some events and update one event
Some user actions are not generating descriptions in the right-most column of the history table on the item view page when an item is saved as a draft or deposited.

Actions not generating a description and what the description should be:
- removing file description: "file description changed"
- removing a contact: "contact email modified"
- removing an author: "authors modified"
- removing a contributor: "contributors modified"
- removing a keyword: "keywords modified"
- removing a related work: "related works modified"
- removing a related link: "related links modified"
- removing a work subtype: "work subtypes modified" (note: I can't verify this one currently because there is a bug preventing me from removing a work type)

Also, there is currently a bug with the 

See https://github.com/sul-dlss/happy-heron/blob/48b1cbe2d1d8faaaae0c8159399a2b5c92c2a0c5/app/services/work_version_event_description_builder.rb#L24-L111

### LINKED ISSUE #2457: [happy-heron/prod] ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "work_id" violates not-null constraint
DETAIL:  Failing row contains (6547, 1, null, data, null, null, null, world, null, CC-BY-SA-3.0, 2022-08-22 18:47:51.703126, 2022-08-22 18:47:51.703126, deposited, null, {}, null, null, null).
## Backtrace

    line 45 of [PROJECT_ROOT]/app/services/migrate.rb: block in run
    line 38 of [PROJECT_ROOT]/app/services/migrate.rb: run

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/77112/faults/87589149)

### PR DESCRIPTION
**Pull request by peetucket**
## Why was this change made? 🤔

Fixes #2304 
- description changes of works that involve associations need some additional logic to detect when one is removed
- description changes of file labels need some additional checks so they operate correctly when a file description is changed to blank, added (but not if added blank), or changed

## How was this change tested? 🤨

Localhost and new tests

Note: only one association (keywords) has complete tests (it had none before) - the others should operate exactly the same way since they all use the same logic/code.

### CODE REVIEW

**Review by ndushay — APPROVED** [review]
needs a rebase, but LGTM.  Approving.

**Comment by peetucket** [comment]
rebased

**Comment by ndushay** [comment]
and now ... failing test.

**Comment by peetucket** [comment]
ugg. unrelated flaky test -- reran and it passed

**Pull request merged**
