### PR TITLE
Change layout of other subtype input.

### LINKED ISSUE #2276: In work type modal, update the free text field that displays when "Other" is selected
When a user selects the "Other" work type option, the free text field that displays should:

1. have an asterisk to the right of the "Specify "Other" type" text, and
2. be centered under the work type options and the same width as those three columns are.

Screen Shot 2022-06-08 at 1 02 25 PM

### PR DESCRIPTION
**Pull request by justinlittman**
closes #2276

## How was this change tested? 🤨

⚡ ⚠ If this change involves consuming from or writing to another service (or shared file system), ***run [integration test create_object_h2_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test manually in [stage|qa] environment, in addition to specs. ⚡

Local

image

### CODE REVIEW

**Comment by justinlittman** [comment]
@amyehodge This is the best that I can do with my CSS skills. Is it close enough?

**Comment by justinlittman** [comment]
@jcoyne I can't get this test to pass. It works fine in the local browser, but isn't displaying in the test.

image

**Comment by justinlittman** [comment]
@amyehodge approved.

**Comment by jcoyne** [comment]
@justinlittman needs a rebase.

**Review by jcoyne — APPROVED** [review]

**Pull request merged**
