### PR TITLE
Revised type mapping

### PR DESCRIPTION
**Pull request by arcadiafalcone**
## Why was this change made?
Part of #1392 

## How was this change tested?
n/a

## Which documentation and/or configurations were updated?
H2 mappings in dor-services-app

Requires further work to update code and other tests to reflect the mapping changes.
Implementation ticket #1435

### CODE REVIEW

**Review by jcoyne — APPROVED** [review]

**Comment by ndushay** [comment]
@arcadiafalcone tests are failing - can you take a look, or would you like to pair?

**Comment by arcadiafalcone** [comment]
The tests are expected to fail - they need to be updated to fit the new mapping.

**Comment by ndushay** [comment]
can you change them to xit "to be implemented for new mapping" ?

**Comment by arcadiafalcone** [comment]
Here you go: https://github.com/sul-dlss/happy-heron/pull/1486

**Pull request merged**
