### PR TITLE
Align look & feel of terms of deposit w/ design doc

### LINKED ISSUE #38: Align terms of deposit in edit form with mock-up
- [x] Shift terms of deposit checkbox to right side of form (see bottom of [work edit form mock-up](https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/420954309))
- [x] Linkify `Terms of Deposit` in checkbox, linking to new [terms of deposit view modal](https://projects.invisionapp.com/share/EQXC9CLKCR2#/screens/433337119)
- [x] Render terms of deposit view modal when link clicked

### PR DESCRIPTION
**Pull request by mjgiarlo**
Peek 2020-11-09 08-31

## Why was this change made?

Fixes #38

Also includes:
* Rename modal component to better describe its function
  * This will reduce friction when creating future modal components.

## How was this change tested?

CI and local browser.

## Which documentation and/or configurations were updated?

None

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@astridu How does the screencap above look? Close enough for me? Or are there changes you'd recommend making? Thanks!

**Comment by astridu** [comment]
@mjgiarlo Looks good! Could we make it just an inch wider? Thank you!

**Review by jcoyne — CHANGES_REQUESTED** [review]
Make wider

**Comment by mjgiarlo** [comment]
@jcoyne @astridu I've widened the ToD modal. See the updated .gif above. Take another look?

**Review by jcoyne — APPROVED** [review]

**Comment by astridu** [comment]
@mjgiarlo Perfect. Thank you!

**Pull request merged**
