### PR TITLE
Update globus instructions

### LINKED ISSUE #3203: Update Globus instructions on item view page
The text in the pink box needs to be updated as follows:

Step 1 should read:

1. If you are NOT transferring content from Oak, Sherlock, or Google Drive, you may need to perform some setup tasks, including installation of software. Check the appendices of our instructions for details. [link "instructions" with the same link we've been using for this] Be sure you have logged into Globus with your Stanford credentials!

### PR DESCRIPTION
**Pull request by lwrubel**
# Why was this change made? 🤔
Resolves #3203 to update instructions for Globus. @amyehodge see below and also questions from @ndushay on #3202.

Screenshot 2023-07-07 at 3 24 27 PM

HOLD until questions on #3202 are resolved since these should likely be in sync. 

# How was this change tested? 🤨
Unit and local instance

⚡ ⚠ If this change involves consuming from or writing to another service (or shared file system), ***run [integration test create_object_h2_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test manually in [stage|qa] environment, in addition to specs. ⚡

# Does your change introduce accessibility violations? 🩺
No
⚡ ⚠ Please ensure this change does not introduce accessibility violations (at the WCAG A or AA conformance levels); if it does, include a rationale. See the [Infrastructure accessibility guide](https://github.com/sul-dlss/DeveloperPlaybook/blob/main/best-practices/infra-accessibility.md) for more detail. ⚡

### CODE REVIEW

**Comment by ndushay** [comment]
Amy and I discussed the wording for #3202 and revised it.  Amy would like you to move the "Be sure you have logged in ..." sentence to be a bullet point under the first step.  That's the only change here.

**Review by ndushay — CHANGES_REQUESTED** [review]
looks good, modulo the change amy requested (see comment above)

**Comment by lwrubel** [comment]
@amyehodge I've updated the wording to be in sync with what @ndushay clarified with you about the globus instructions. Will take [HOLD] off this once you've had a chance to take a look. 

Screenshot 2023-07-10 at 7 55 40 AM

**Comment by amyehodge** [comment]
@lwrubel This looks good. Thanks!

**Review by ndushay — APPROVED** [review]

**Pull request merged**
