### PR TITLE
Email validation

### PR DESCRIPTION
**Pull request by laasem**
## Why was this change made?
Fixes https://github.com/sul-dlss/happy-heron/issues/171 by validating that the collection and work `contact_email` is a valid email using the built-in Ruby URI library's `MailTo::EMAIL_REGEXP`

## How was this change tested?
By adding unit tests in `collection_spec.rb` and `work_spec.rb`

## Which documentation and/or configurations were updated?
None

### CODE REVIEW

**Review by jcoyne — APPROVED** [review]
Thanks @laasem this looks great.

**Comment by jcoyne** [comment]
@laasem can you rebase these changes to resolve the conflict?

**Comment by mjgiarlo** [comment]
> @laasem can you rebase these changes to resolve the conflict?

I've resolved the conflicts. Thank you for these changes!

**Comment by laasem** [comment]
Thanks for reviewing! I've resolved the remaining conflicts as well.

**Comment by mjgiarlo** [comment]
@laasem thanks again!

**Pull request merged**
