### PR TITLE
Switch to using Ruby 3

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Review by mjgiarlo — APPROVED** [review]
:cool:

**Comment by jcoyne** [comment]
Sorbet does not support ruby 3.0 yet: https://github.com/sorbet/sorbet/issues/3851

**Comment by ndushay** [comment]
Can/should this be closed?  Please do so and delete branch if so.

**Comment by jcoyne** [comment]
We're planning on merging this in the maintenance week in Jan.

**Pull request closed without merging**
