### PR TITLE
Require the email to be entered before the title is marked as complete

### LINKED ISSUE #957: "Title" section of progress bar on dashboard should consider entries for both title and email
The "Title" section of the progress bar should not be green unless BOTH the title and the email contact in this section have content in them. Right now it is only considering the title.

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?

Fixes #957

### CODE REVIEW

**Review by mjgiarlo — COMMENTED** [review]
Do we also need changes to the edit_deposit_controller so that the client-side behavior is consistent with the server-side behavior change?

**Comment by jcoyne** [comment]
@mjgiarlo ticket #957 was specifically about the dashboard.

**Comment by mjgiarlo** [comment]
@jcoyne :speech_balloon: 
> @mjgiarlo ticket #957 was specifically about the dashboard.

That change needn't be in this PR. I can write up an issue.

**Comment by jcoyne** [comment]
@mjgiarlo I think that would be covered in #935

**Review by mjgiarlo — APPROVED** [review]

**Pull request merged**
