### PR TITLE
Adjust globus confirm sizing.

### LINKED ISSUE #2954: Make check box and text for confirming Globus file transfer bigger
When users return to confirm that files have been uploaded to Globus, display a box in the Globus section of the Add files portion of the page. This box should include a check box and the text:

"Check this box once all your files have been uploaded to Globus." 

This should display under the series of instructional steps and be much bigger than what has currently been implemented.

See second screenshot under step 6 at https://projects.invisionapp.com/share/YQ132HXFX2GR#/screens/471628807_Globus_Integ_Enh

### PR DESCRIPTION
**Pull request by justinlittman**
closes #2954

## Why was this change made? 🤔
Per PO.

## How was this change tested? 🤨

⚡ ⚠ If this change involves consuming from or writing to another service (or shared file system), ***run [integration test create_object_h2_spec.rb](https://github.com/sul-dlss/infrastructure-integration-test)*** and/or test manually in [stage|qa] environment, in addition to specs. ⚡

image

### CODE REVIEW

**Comment by justinlittman** [comment]
@amyehodge Does this look OK?

**Review by mjgiarlo — APPROVED** [review]

**Comment by amyehodge** [comment]
@justinlittman Where can I see the change? The screenshot above doesn't appear to show it.

**Comment by justinlittman** [comment]
Before:
image

After:
image

**Comment by amyehodge** [comment]
@justinlittman This looks to be missing 3 things from the design:
1. The change to the text. This should read "Check this box once you have uploaded all of your files to Globus."
2. This should be indented to the right so that it appears to be more a part of the third file upload option.
3. The design has a box around this checkbox and text. This is the least important piece to implement, but makes more sense with the rest of the design shown in the ticket #2954 where there are other boxes above this one.

**Comment by amyehodge** [comment]
@justinlittman Upon reflection I've realized this was not a very well-written ticket. Apologies for that.

**Comment by justinlittman** [comment]
Ahh, how about this @amyehodge ?
image

**Comment by amyehodge** [comment]
@justinlittman Looks awesome. Thanks so much for the revisions.

**Pull request merged**
