### PR TITLE
Switch from Rubocop to Standard for linting

### PR DESCRIPTION
**Pull request by mjgiarlo**
## Why was this change made? 🤔

We're gradually making the switch and we're about to spend a work cycle in H2. Why not now?

## How was this change tested? 🤨

CI

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@justinlittman 💬 
> Approve, but are there any PRs that should go in before this?

I see @peetucket has a couple that are ready-ish. I'll work with him to get those in before this one.

**Comment by peetucket** [comment]
Is this one still relevant ?  #2867 (adds erb linting)

**Comment by mjgiarlo** [comment]
@peetucket 💬 
> Is this one still relevant ? #2867 (adds erb linting)

I'm going to pick that one up and update it after this PR gets merged.

**Comment by mjgiarlo** [comment]
All pending, ready PRs that are likely to be affected by these changes have now been merged, which unblocks this PR. Merging when green. Thanks, all.

**Pull request merged**
